### ISSUE TITLE
Allow wildcard in email address aliases

### ISSUE THREAD

**Issue by IGLOU-EU** [algoo/galae#3]
### Summary

This feature would allow domain owners to create email address aliases that match a wildcard pattern.
For example, if I have an email address `ellen@wayland-yutani.terre`, I should be able to create an alias `ellen*@wayland-yutani.terre -> ellen@wayland-yutani.terre`
That way, I can give out email addresses like `ellen-facebooktracking-junk@wayland-yutani.terre`

### Motivation

This feature is request by Algoo for the Galae project.

### Additional context

To implement this feature, we need to add two things into the UI:
- A new option into the domain configuration of the global administrator. To avoid confusion, we should call it "wildcard aliases" or something similar. The option should be a boolean, and it should be disabled by default to preserve the current behavior.
- A information point into the alias creation form, to explain the feature is available (or not) for the current domain. And a red mark when a wildcard alias is present in the alias listing.

See the mockup below for an example of the UI:
![Screenshot 2023-09-14 at 15-14-21 mailcow UI](https://github.com/algoo/galae/assets/15379333/7e1bb68f-53ad-4d67-a7bd-abf56f1d8cf9)

![Screenshot 2023-09-14 at 15-20-58 mailcow UI](https://github.com/algoo/galae/assets/15379333/3dbe0de0-7420-4581-af71-72ef1c54c375)

![Screenshot 2023-09-14 at 17-00-35 mailcow UI](https://github.com/algoo/galae/assets/15379333/7c678d6d-dde9-4198-b041-7e35d8b27cc5)

**Comment by lebouquetin** [comment]
@IGLOU-EU it's ok like this. As we talked, let's implement it like this, with the possiiblity to disable the feature for the global admin.

**Comment by lebouquetin** [comment]
Hello @IGLOU-EU , I'm pretty sure you sent me some news about something probably being available by the end of the week ... but impossible to find the information back ...

**Comment by IGLOU-EU** [comment]
Hi @lebouquetin yes I have some news, check it in #4 
I expect to have something to test at the end of the week, I EXPECT :hurtrealbad:
